# Generated by Django 5.2.15 on 2026-06-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayerwinner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prayerrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'refused')], default='pending', max_length=20),
        ),
    ]
