# Generated by Django 5.2.15 on 2026-06-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0002_alter_churchsettings_id'),
        ('settings_app', '0002_major_event_fields'),
    ]

    operations = [
    ]
